# Following this article https://www.fermyon.com/wasm-languages/zig

spin_version = "1"
authors = ["Diogo Neves <diogo.neves@gmail.com>"]
description = "A simple example of Tangle synchronisation in a Zig"
name = "tangled-wig"
trigger = { type = "http", base = "/" }
version = "1.0.0"

[[component]]
source = "main.wasm"
id = "tangled-wig"
[component.trigger]
route = "/wig"
executor = { type = "wagi" }